name: 'Simple Test Result'
description: 'Shows if tests passed or failed with a friendly message'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        if [ $? -eq 0 ]; then
          echo " Awesome! All tests passed! "
          echo " Good job! Your code is working great!"
        else
          echo " Oops! Some tests failed"
          echo " Check the test output above for details"
        fi