name: Node.js Tests

on:
  push:
    branches: [  master ]
  pull_request:
    branches: [  master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run all tests
      run: npm test
      
    - name: Run specific test files
      run: |
        npm test tests/devide.test.js
        npm test tests/emailValidator.test.js
        npm test tests/substract.test.js
        npm test tests/userDatabaseHooks.test.js