name: Complete Secure Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit

      - name: Run tests
        run: npm test

      - name: Check code quality
        run: |
          npm run lint
          npm outdated

  # This job will only run on pull requests
  approval:
    needs: verify
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check pull request reviews
        uses: actions/github-script@v7
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const approved = reviews.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed('Pull request needs approval before merging');
            }

      - name: Check for open comments
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            if (comments.length > 0) {
              core.setFailed('All comments must be resolved before merging');
            }

  # This job will only run on push to main
  publish:
    needs: verify
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
      
    # - name: Run specific test files
    #   run: |
    #     npm test tests/devide.test.js
    #     npm test tests/emailValidator.test.js
    #     npm test tests/substract.test.js
    #     npm test tests/userDatabaseHooks.test.js